### ISSUE TITLE
Allow comma as completion_char as well as colon

### ISSUE THREAD

**Issue by grifferz** [chrisjrob/sluggle#18]
Currently in order to address the bot you must use its nickname and a colon:

```
<grifferz> sluggle: test
<sluggle> grifferz: https://www.speedtest.net/ - Speedtest.net by Ookla - The Global Broadband Speed Test.
```

I have a comma as my `completion_char` set in irssi though, and that doesn't work:

```
<grifferz> sluggle, test
```

(no response)

So please could the regular expressions be updated with [:,] instead?

**Comment by chrisjrob** [comment]
Already done, see commit 7a298266d744a491273ebd211d7edd5f5d285769
