### ISSUE TITLE
Should not respond to other bot's ! commands

### ISSUE THREAD

**Issue by domcleal** [chrisjrob/sluggle#22]
<pre>
004552 <+shmoo> !aq canal
004552 -Enoch:#bitfolk- Quote[5062 / ....
004554 < sluggle> shmoo: https://canalrivertrust.org.uk/enjoy-the-waterways/canal-and-river-network/regents-canal - Regent's Canal
</pre>

It looks like the regexes at https://github.com/chrisjrob/sluggle/blob/b233e95/sluggle.pl#L191 don't require that `!` is followed by a particular command or any whitespace, so it matches anything starting with `!`.

I'm not certain what the intention of that was - should it match `!sluggle` or also stuff like `!find`?  If the former then it should probably be `/^(?:!$whoami\s|$whoami[:,])\s*(.+)$/i` or similar.

**Comment by chrisjrob** [comment]
Thanks Dominic. All fixed.
