### ISSUE TITLE
Ignore AgainstHumanity

### ISSUE THREAD

**Issue by domcleal** [chrisjrob/sluggle#26]
<pre>
102849 <@Dave2> AgainstHumanity: thanks for that handy PM reminder it was very useful I had forgotten I needed to pick winners.
102849 <+AgainstHumanity> Dave2: Sorry, that's not a command I recognise. See https://github.com/grifferz/pah-irc#usage for more info.
102852 < sluggle> AgainstHumanity: http://tinyurl.com/zhge7vs - GitHub - grifferz/pah-irc: Perpetually Against Humanity, IRC Edition.
102852 <+AgainstHumanity> sluggle: Sorry, that's not a command I recognise. See https://github.com/grifferz/pah-irc#usage for more info.
102853 -!- sluggle [~cjr@jepgmbcrx.bootpolish.net] has quit [Remote host closed the connection]
</pre>

A couple of things - a) ignore AgainstHumanity, b) it crashed trying to search for that long phrase?

**Comment by chrisjrob** [comment]
Thanks Dominic. I have added AgainstHumanity, Enoch and Twitfolk to the botlist in conf. I will open a separate issue for the fact that it crashed on a malformed JSON response - Issue #27 .
