### ISSUE TITLE
Net::WolframAlpha; doesn't exist

### ISSUE THREAD

**Issue by popey** [chrisjrob/sluggle#36]
sluggle requires Net::WolframAlpha; but it seems that's not installable from cpan, and perhaps is now WWW::WolframAlpha?

**Comment by chrisjrob** [comment]
Pretty sure I downloaded that from Wolfram Alpha themselves.

**Comment by chrisjrob** [comment]
http://products.wolframalpha.com/api/libraries.html

**Comment by chrisjrob** [comment]
Assume that resolved the issue, so closing, let me know if not Alan.
