### ISSUE TITLE
Make default action a search

### ISSUE THREAD

**Issue by grifferz** [chrisjrob/sluggle#4]
The bot that this is repalcing (find) treats everything that's not a command as a search request, so:

```
<grifferz> find, test
<find> test: http://www.speedtest.net/
```

I think that is nicer than having to do:

```
<grifferz> sluggle: find test
```

**Comment by chrisjrob** [comment]
I could do that, the only problem is the lack of tab-complete if I use an arbitrary command.

I could rename the bot to "find", so that tab complete works, but then that would be in conflict with the old find bot. Open to ideas.

**Comment by grifferz** [comment]
I'm a bit confused what you mean. I'm proposing that:

```
<grifferz> sluggle, the aristocrats
```

be exactly the same as if I had done:

```
<grifferz> sluggle: find the aristocrats
```

or

```
<grifferz> !find the aristocrats
```

I don't care what the bot is called, I just find it more natural to address it as if it is a person rather than type !somecommand and hope that I remember which bot is looking for that one. And then once it knows it is being addressed, what is the point of requiring the word "find" there?

**Comment by chrisjrob** [comment]
I'm with you. Well that can be configured from the conf file, just literally changing "addressed 0" to "addressed 1". It won't then permit !find - so it would be a choice per parameter file.

Unfortunately the conf file is by server, not by channel, so need to think about how to allow some channel customisation.
