### ISSUE TITLE
Bot should join channels when invited and leave them when kicked

### ISSUE THREAD

**Issue by grifferz** [chrisjrob/sluggle#5]
Multiple channels on the same network will most likely have an interest in Sluggle, so I think that it should join channels when invited, stay in them while it thinks it is wanted, and stay out of them after being kicked out.

**Comment by chrisjrob** [comment]
Resolved by commit b901966d8c6c274a7c2306f5fadb32a22a6ee729 but only tested as far as kicking and inviting, not tried communicating from different channels yet.

**Comment by chrisjrob** [comment]
Sorry hopeless combined commit, must get better at committing!

**Comment by domcleal** [comment]
> Sorry hopeless combined commit, must get better at committing!

Today's top tip: `git add -p`, `git ci -m "First bit"`, rinse and repeat.

**Comment by grifferz** [comment]
Won't this lose the list of channels it should be in as soon as the process exits?

**Comment by chrisjrob** [comment]
Quite right - fixed (again) in commit 3c4c7fc.

**Comment by chrisjrob** [comment]
Thanks @domcleal for that tip.

**Comment by chrisjrob** [comment]
Just a thought - should I check that the inviter is a channel op?

**Comment by grifferz** [comment]
I don't think that is necessary; normally only ops can invite people to channels. The fact that you got an invite means it is allowed.

**Comment by chrisjrob** [comment]
Thank you.
