### ISSUE TITLE
Consider blacklists

### ISSUE THREAD

**Issue by chrisjrob** [chrisjrob/sluggle#9]
Could be configured via the bot possibly including regex bans of sites.

**Comment by grifferz** [comment]
What are you thinking of protecting against?

**Comment by chrisjrob** [comment]
Truth is I don't know, I felt very vulnerable when people were throwing dodgy URLs at it, and wondered whether an admin option to block a site would be worthwhile. On reflection I think perhaps micro-managing is not the answer.

**Comment by grifferz** [comment]
Possibly you could consider banning ports in URLs (except 80 and 443) if you don't want people to be able to tell it to connect to an arbitrary TCP port and do a GET request. But other than that it's just being a very limited web browser so I'm not sure what you'd want to ban…

**Comment by chrisjrob** [comment]
I only permit ports 80 and 443, so I guess that's sorted. I'll close this issue then.
